import express from "express";
import { createServer as createViteServer } from "vite";
import { RouterOSAPI } from "node-routeros";
import cors from "cors";
import bodyParser from "body-parser";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(cors());
  app.use(bodyParser.json());

  // MikroTik API Route
  app.post("/api/mikrotik/generate", async (req, res) => {
    const { host, user, password, port, count, profile, prefix, length, type } = req.body;

    const conn = new RouterOSAPI({
      host,
      user,
      password,
      port: parseInt(port) || 8728,
      timeout: 10,
    });

    try {
      await conn.connect();
      const generatedUsers = [];

      for (let i = 0; i < count; i++) {
        const username = prefix + Math.random().toString(36).substring(2, 2 + length);
        const pwd = type === 'user_pass' ? Math.random().toString(36).substring(2, 2 + length) : username;

        if (req.body.mode === 'usermanager') {
          // Add user to User Manager (v6 syntax, v7 is different but this is common)
          await conn.write("/tool/user-manager/user/add", [
            `=customer=admin`,
            `=username=${username}`,
            `=password=${pwd}`,
            `=comment=Generated by App`
          ]);
          // Add profile to user
          await conn.write("/tool/user-manager/user/create-and-activate-profile", [
            `=customer=admin`,
            `=user=${username}`,
            `=profile=${profile}`
          ]);
        } else {
          // Add user to Hotspot
          await conn.write("/ip/hotspot/user/add", [
            `=name=${username}`,
            `=password=${pwd}`,
            `=profile=${profile}`,
            `=comment=Generated by App`
          ]);
        }

        generatedUsers.push({ username, password: pwd, profile });
      }

      await conn.close();
      res.json({ success: true, users: generatedUsers });
    } catch (error: any) {
      console.error("MikroTik Error:", error);
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Get Profiles Route
  app.post("/api/mikrotik/profiles", async (req, res) => {
    const { host, user, password, port, mode } = req.body;

    const conn = new RouterOSAPI({
      host,
      user,
      password,
      port: parseInt(port) || 8728,
      timeout: 10,
    });

    try {
      await conn.connect();
      let profiles;
      if (mode === 'usermanager') {
        profiles = await conn.write("/tool/user-manager/profile/print");
      } else {
        profiles = await conn.write("/ip/hotspot/user/profile/print");
      }
      await conn.close();
      res.json({ success: true, profiles });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
